name: shop_manager
description: "Offline-first retail shop management foundation."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  sqflite: ^2.4.4
  path: ^1.9.1
  uuid: ^4.6.0
  cryptography: ^2.9.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.3

flutter:
  uses-material-design: true
